#!/usr/bin/env bash

# Copyright (C) 2020 Daniel Berg <mail@roosta.sh>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# ====================================

# TODO pass path
# TODO ag and rg compat

CURRENT_DIR=$(cd "$(dirname "$(realpath "$0")")" && pwd)
FIF_FZF_DEFAULT_OPTS="
$FZF_DEFAULT_OPTS
--ansi
--bind='ctrl-s:toggle-sort'
--bind='?:toggle-preview'
--preview-window=up
$FIF_FZF_DEFAULT_OPTS
"

fif::cat_cmd() {
  if hash rg 2>/dev/null; then
    rg \
      --line-number \
      --hidden \
      --color never \
      --no-heading .
  elif hash ag 2>/dev/null; then
    ag --line-number .
  else
    grep
  fi
}

fif::fzf_cmd() {
  local opts
  opts="
      $FIF_FZF_DEFAULT_OPTS
      -d \":\"
      --nth \"2..\"
      --with-nth \"1,3..\"
      --preview=\"$CURRENT_DIR/preview.sh {}\"
    "
  FZF_DEFAULT_OPTS="$opts" fzf
}

fif::find_in_files() {
  local location
  location="$1"
  if [ -d "$1" ]; then
    (
      cd "$location" &&
        match=$(fif::cat_cmd | fif::fzf_cmd) &&
        linum=$(echo "$match" | cut -d':' -f2) &&
        file=$(echo "$match" | cut -d':' -f1) &&
        ${EDITOR:-vim} +"$linum" "$file"
    )
  else
    match=$(fif::cat_cmd | fif::fzf_cmd) &&
      linum=$(echo "$match" | cut -d':' -f2) &&
      file=$(echo "$match" | cut -d':' -f1) &&
      ${EDITOR:-vim} +"$linum" "$file"
  fi

}

fif::exit_if_unsupported() {
  local version version_only_digits supported_version supported_version_only_digits
  if hash fzf 2>/dev/null; then
    version=$(fzf --version | awk '{print $1}')
    version_only_digits=$(echo "$version" | tr -dC '[:digit:]')
    supported_version="0.18.0"
    supported_version_only_digits=$(echo "$supported_version" | tr -dC '[:digit:]')
    if [ "$version_only_digits" -lt "$supported_version_only_digits" ]; then
      echo "fif: Unsupported fzf version ($version), upgrade to $supported_version or higher" >&2;
      exit 1;
    fi
  else
    echo "fif: fzf needs to be installed for this script to work" >&2; exit 1;
  fi
  if hash bat 2>/dev/null; then
    version=$(bat --version)
    version_only_digits=$(echo "$version" | tr -dC '[:digit:]')
    supported_version="0.10.0"
    supported_version_only_digits=$(echo "$supported_version" | tr -dC '[:digit:]')
    if [ "$version_only_digits" -lt "$supported_version_only_digits" ]; then
      echo "fif: Unsupported bat version ($version), upgrade to $supported_version or higher" >&2;
      exit 1;
    fi
  else
    echo "fif: bat needs to be installed for this script to work" >&2; exit 1;
  fi
  command -v rg >/dev/null 2>&1 || { echo "fif: rg needs to be installed for this script to work" >&2; exit 1; }
}

main() {
  fif::exit_if_unsupported
  fif::find_in_files "$@"
}

main "$@"
