#+TITLE: fif: find in files
* Requirements
  Make sure that [[https://github.com/junegunn/fzf][fzf]] version [[https://github.com/junegunn/fzf/releases/tag/0.18.0][0.18.0]] or above is installed.
* Optional
** Concatenation
   For file concatenation either [[https://github.com/BurntSushi/ripgrep][rg]] or [[https://github.com/ggreer/the_silver_searcher][ag]] is optionally required, and
   fif will fall back to grep if none of those are present. I
   recommend using [[https://github.com/BurntSushi/ripgrep][rg]] or [[https://github.com/ggreer/the_silver_searcher][ag]] since those two respect things like git
   ignore and hidden files. Most options passed to these tools are
   configurable. More on that below.
** Preview
   [[https://github.com/sharkdp/bat][bat]] version [[https://github.com/sharkdp/bat/releases/tag/v0.10.0][0.10.0]] or above is optionally require to syntax
   highlight the preview window, if bat isn't present fif will fall
   back...
* Installation
** ZSH Plugin manager
*** [[https://github.com/zplug/zplug][zplug]]
    #+BEGIN_SRC sh
      zplug 'roosta/fif'
    #+END_SRC
*** [[https://github.com/tarjoilija/zgen][zgen]]
    #+BEGIN_SRC sh
      zgen load 'roosta/fif'
    #+END_SRC
*** [[https://github.com/zsh-users/antigen][Antigen]]
    #+BEGIN_SRC sh
      antigen bundle 'roosta/fif'
    #+END_SRC
*** Manual installation
    Clone this repository somewhere and source ~fif.plugin.zsh~ or
    ~fif.plugin.sh~ in your shell config.
* Demonstration
* Usage
* Configuration
** Default keybinds
   | keybind | action                         |
   |---------+--------------------------------|
   | Enter   | Confirm and open file location |
   | Ctrl-s  | Toggle sort                    |
   | ?       | Toggle preview                 |
** Options
* Attribution
** Forgit
   Used [[https://github.com/wfxr/forgit][forgit]] as an example on how to do zsh plugins and how to
   handle options. Also took some pointer from its [[https://github.com/wfxr/forgit/blob/master/README.md][README]].
